Repository anassri/All-A-Bot, pull requests merged in 2020-10, with the labels that each got.

#19 Add dashboard
  app/__init__.py
  app/api/bots.py
  client/src/constants/index.js
  client/src/pages/Dashboard.js
  client/src/pages/Pages.js
  client/src/store/auth.js
  client/src/store/bots.js
  client/src/store/configureStore.js
Labels: enhancement

#20 Auth
  app/routes/auth.py
  client/src/pages/LoginPage.js
  client/src/pages/SignupPage.js
  client/src/store/auth.js
Labels: bug

#33 [Auth] Auth bugs
  .env.example
  app/config.py
  client/src/components/Navigation.js
  client/src/pages/LoginPage.js
Labels: bug

#44 Display bots in dashboard
  client/src/store/bots.js
Labels: bug

#39 Redirect to / after logout
  client/src/components/Navigation.js
Labels: bug

#46 [Main] Individual bot view
  app/__init__.py
  app/api/bots.py
  client/src/components/Navigation.js
  client/src/constants/index.js
  client/src/images/background.svg
  client/src/pages/Bot.js
  client/src/pages/Explore.js
  client/src/pages/Pages.js
  client/src/store/bots.js
  client/src/style/index.css
Labels: enhancement

#47 Updated "create bot" link
  client/src/components/Navigation.js
  client/src/pages/CreateBot.js
  client/src/pages/Pages.js
Labels: bug

#58 [Search] Users can search for a bot by name or description
  client/src/pages/Explore.js
Labels: enhancement

#68 [Auth] Oauth2
  Pipfile
  Pipfile.lock
  app/oauth.py
  app/routes/auth.py
  client/src/pages/LoginPage.js
  client/src/pages/Pages.js
  client/src/pages/Redirect.js
  client/src/store/auth.js
Labels: enhancement

#83 fix pre-loading and redirect after saving a new bot
  client/src/pages/EditBot.js
Labels: bug

#79 [Response] Add role to a member
  client/src/components/Guide.js
  client/src/pages/Dashboard.js
  client/src/pages/EditBot.js
  client/src/utils/fileSaver.js
  client/src/utils/templateCreator.js
  database.py
Labels: enhancement

#85 [Response] Remove role from a member
  client/src/pages/EditBot.js
  client/src/utils/templateCreator.js
  database.py
  migrations/versions/20201026_140538_.py
Labels: enhancement

#86 Fix create button so it always goes to a blank form
  app/api/bots.py
  client/src/constants/index.js
  client/src/pages/CreateBot.js
  client/src/store/bots.js
Labels: bug

#102 [Styling] Styling tweaks, minor bug fixes, button adding and refactoring
  client/src/App.js
  client/src/components/DownloadBtn.js
  client/src/components/Footer.js
  client/src/images/footer.svg
  client/src/pages/Bot.js
  client/src/pages/Dashboard.js
  client/src/pages/EditBot.js
  client/src/pages/Explore.js
  client/src/pages/LoginPage.js
  client/src/pages/SignupPage.js
  client/src/style/index.css
  client/src/theme.js
  database.py
Labels: bug, enhancement, style

#107 [Styling, Edit Form, Main] Added remove buttons, fixed styling, refactored download button
  client/src/App.js
  client/src/components/DownloadBtn.js
  client/src/components/Footer.js
  client/src/images/footer.svg
  client/src/pages/Bot.js
  client/src/pages/BotSuccess.js
  client/src/pages/Dashboard.js
  client/src/pages/EditBot.js
  client/src/pages/Explore.js
  client/src/pages/LoginPage.js
  client/src/pages/Pages.js
  client/src/pages/SignupPage.js
  client/src/style/index.css
  client/src/theme.js
  database.py
Labels: bug, enhancement, refactor, style

#110 [Edit Form, Main] Added remove button, edited about section
  client/src/pages/EditBot.js
  client/src/pages/Explore.js
Labels: bug, enhancement

#109 [Dash] Make bots in draft and bookmark panels clickable
  client/src/pages/Dashboard.js
Labels: bug

#111 [Dash] Prevent redirect after delete
  client/src/pages/Dashboard.js
Labels: bug
